### PR TITLE
Fixed #10: use implicit parameter callstacks

### LINKED ISSUE #10: consider using recent ghc's callstack to get call-site information instead of TH

### PR DESCRIPTION
**Pull request by adinapoli**
@MichaelXavier , @ozataman hey folks!

I had 1 hour of spare hacking time, so I thought about contributing to Katip on a low-hanging fruit :wink: 

This PR delivers a minimal rewrite of the `getLoc` function to remove the need for TH, using implicit-parameters and the `GHC.Stack` module to retrieve the callstack. The end result between the TH-driven and the srcLoc-driven output is the same (from `katip/examples/example.hs):

screen shot 2016-04-03 at 19 03 08

screen shot 2016-04-03 at 19 29 32

What we gained is, of course, that there is no need anymore for calling `logT` and `logTM` with the TH splicing syntax, which makes the API a little nicer. 

#### The technical implementation

I have adopted the path of least resistance, and `getLoc` simply converts a `SrcLoc` into a `Loc`. This is mostly to not break the existing API, but also because the current code assumes we can construct a `Loc` in the marshalling code, but [SrcLoc](https://hackage.haskell.org/package/base-4.8.2.0/docs/GHC-SrcLoc.html#t:SrcLoc) has no exposed constructor. That's why I ended up with the current implementation. To recap what this PR delivers:

* A rewrite a `getLoc` using [GHC.Stack.Callstack](https://hackage.haskell.org/package/base-4.8.2.0/docs/GHC-Stack.html), reusing the existing code as much as possible.

* Does **not** bump the package version, as usually this is done by package maintainers

* Ported all the examples, docs and code to use the "new" syntax for `logT` and `logTM` (no need for TH)

* Does **not** remove the `TH.Lift` instances we had in place originally. I haven't tried removing them, but I guess it does no harm in keeping them (aka I don't know if they were needed only for logT/logTM or also for other TH invokations)

<hr/>

Last but not least, if you think this is not the way to go or using the implicit-params callstack is not a good idea at all don't worry, I won't hold anything against you :wink: It was a fun exercise in an-otherwise-boring afternoon.

Alfredo

### CODE REVIEW

**Comment by mightybyte** [comment]
At first glance I really like the intent of this idea.  I have been adding Katip logging to an application I work on and part of this has included my own app-specific wrapper around Katip's `logTM`.  But in doing so I couldn't help but wonder if the line numbering would be made useless if logTM gets the location of my generic function instead of the location at each use site.  Using call stack seems like it would eliminate this concern, so it sounds like a nice improvement to me.

**Comment by adinapoli** [comment]
@mightybyte Thanks! Although all the credits for the idea goes to @ibotty, I was the mere executor :wink:

**Comment by MichaelXavier** [comment]
@adinapoli Thanks for this work. This looks great. One possible thing that could throw a wrench in here is that we support 7.8 and 7.10 at the moment. I'm not 100% sure that this functionality is available there. I'm working on getting travis to run our build on a 7.8 LTS to make sure we don't break anything. I think the alternative may be to keep the TH and have it use callstacks under the covers if they're available, though I'm not sure if that defeats the purpose. We could drop 7.8 support but this seems like kind of a minor reason to do so.

**Comment by adinapoli** [comment]
> One possible thing that could throw a wrench in here is that we support 7.8 and 7.10 at the moment.

Good point! It was a concern of mine as well, which I have forgot to include in the PR as well. I'm unsure (aka I haven't tested, going only by gut feeling) that `CallStack` is a ghc >= 7.10 feature, as in the docs it says "Since: 4.9.0.0" but perhaps confusingly enough the docs I'm browsing is for [base-4.8.2.0](https://hackage.haskell.org/package/base-4.8.2.0/docs/GHC-Stack.html), so yea, I think hands-on testing is the best bet :wink: 

 >  I think the alternative may be to keep the TH and have it use callstacks under the covers if they're available, though I'm not sure if that defeats the purpose. We could drop 7.8 support but this seems like kind of a minor reason to do so.

Yea, agreed. In theory we could use `CPP` to have 2 different versions of the API according to which version one is using, but that seems gross, as it would cause user confusion about which API to use (`logT` vs `logTM`), but of course I'm happy to do that, if we feel this might be a suitable path to take, and remove the "legacy" API when we drop 7.8 support.

**Comment by MichaelXavier** [comment]
@adinapoli after the customary several dozen commits to get the thing building with travis, master now has a working travis setup for 7.8. I was able to test your branch locally with it:

```
export ARGS="--stack-yaml=stack-7.8.yaml"
stack $ARGS setup && stack $ARGS test --no-terminal --haddock --no-haddock-deps && stack $ARGS bench && stack $ARGS build
```

And this fails out being unable to find the module `GHC.SrcLoc`, which appears to be introduced in base-4.8. So maybe the best approach is to keep the TH for now but under the covers have it use implicit callstacks for newer GHCs. I think you'd want CPP like `#if MIN_VERSION_BASE(4, 8, 0)`. You could even mention in the function docs that the functions use implicit callstacks in recent versions of haskell and that TH will no longer be used in the future.

As far as when we'll drop support, @ozataman please weigh in if you disagree but I think its prudent to support the current GHC version and the one prior (so 7.10 and 7.8, with no support for 7.6). Given the release cadence of GHC this seems like it gives ample time for users to upgrade without putting a ton of strain on us to backport features. Once the next version comes out (8.0?), we'd slowly start dropping 7.8 support. Normally, I'd probably go with a deprecation release that warns on the old API, but I think this callstack feature is a syntactical change, so it may not be feasible to have a version  that has both APIs active at once.

**Comment by ibotty** [comment]
Alternatively one could offer a non-th api which does not handle the source location when on older GHC releases.

**Comment by MichaelXavier** [comment]
@ibotty that's a good point. So maybe we'd keep the TH for now and when we drop 7.8 support, we put a deprecation warning on the TH function, add a non-TH function that has no source info when you don't have implicit callstacks, and then in the next release, drop TH and drop the CPP you use to accomplish that.

**Comment by adinapoli** [comment]
@ibotty @MichaelXavier I think I've got you guys. Trying to summarise what I think we are in agreement upon as the most conservative plan for now:

* I will rework this PR to **not** get rid of the splicing for `logT` and `logTM` (so they effectively will still yield an `ExprQ`), but I will implement the source location in terms of implicit callstacks, if available, using a `CPP` pragma. This will ensure we do the initial work towards supporting them (and dropping eventually 7.8), but without breaking our current API or dropping 7.8 support. I will make sure to document in the Haddock docstring the internal implementation (as per Michael's comment).

* We merge the reworked PR and live long and prosper. We optionally keep #10 open (or we create a different ticket) to remind ourselves to tackle the migration to implicit callstacks only at the right time in the future

* When GHC 8.0 gets released (or when we decide to drop 7.8) , we come back to this issue and we add a non-TH API (name to be decided, I guess). At this particular point in time we will have 2 API co-existing in the codebase:
    1. The TH one, which will get a `DEPRECATED` pragma to warn the user it will go away in future releases
    2. The non-TH one, which will use implicit callstacks for GHC > 7.8, but defaults to a no-op in case it's used with older GHCs, where the callstacks are not available. This will be accomplished, once again, via `CPP`.

* We release a new version which officially drops 7.8. At this point in time:
    1. We remove the TH API
    2. We remove the `CPP` so that the non-TH API will be the only and de-facto API which will always have source locations available via implicit callstacks.

Does this sound about right folks or did I miss your point? 

My only final concern is about the non-TH API. How shall it be named? I'm worried that whichever name we use it will need to stay stable for future versions of the library, as the user will probably expect to migrate with minor hassle (i.e. simply removing the splicing from the calls to `logT` and `logTM`), so I guess we should put extra care in this, but I guess it's not a concern for this PR.

**Comment by ibotty** [comment]
I am in agreement but for one little point.

Why wait for the non-TH api? Add it now, using source locations when available, or without when not. That way, deprecation is not even necessary. People that are on new-enough ghc (or don't care for source location) can just use the non-TH api right away; people that are on older ghc, can use the TH api. No need to deprecate anything.

Of course that makes it one of the three hard problems of computer-science.

**Comment by adinapoli** [comment]
> Why wait for the non-TH api? Add it now, using source locations when available, or without when not. 

Good point, although maybe Michael wants to go with the past of least resistance here. After all, adding new functions to an API, which the user is gonna use from here until the foreseeable future is something to not be taken lightly, if one wants care about stability.

In case we feel adding these new functions is something we should do as part of this PR, what about using the classic "prime" naming? One would have then 4 functions: `logT`, logT'`, `logTM`, `logTM'`.

Now that I think about it, we should do something even more sneaky; listen up folks:

1. We **rename** the TH API to have the prime notation; this might seems awkward at first but I will explain why in a minute

2. We add the non-TH functions giving them first class names, them being `logT` and `logTM`.

3. We add a `DEPRECATED` pragma to the prime, TH functions.

4. When the time will come, we simply remove the TH functions, and we implement the non-TH properly (without any CPP needed for per GHC 7.8)

5. (Bonus) We use `CPP` to **not export** the non-TH API for older GHC. This way we prevent users on old compiler to shoot themselves in the foot using an API which won't give them source locations.

The slight advantage of this approach is that it will break the user code now but in a trivial way; migration to this new version of Katip is as easy as adding a "prime" everywhere, but they will get the deprecation straight away and changes are they will migrate immediately (unless they are on an old compiler).

Does this seems convoluted or a suitable masterplan?

**Comment by ibotty** [comment]
Some people like to keep their code warning-free for the last 3 GHC releases, so that would preclude that part of the plan. I do like it though.

One additional point regarding the CallStack api, what do you think about exposing all the call stack that you have? That would be more of a restructuring though.

**Comment by MichaelXavier** [comment]
I personally think last 3 GHC releases is a bit excessive given that GHC 7.6.3 was released in 2013, but maybe that's my web dev side showing ;) @ibotty makes a very good point that this could be an additive API change which makes it opt in and thus you don't have to worry so much about deprecation. One bit of insight is that in `logT`, the `T` is for template haskell, and `logTM` is the monadic context version of `logT`. So maybe our original naming was a bit short sighted but this could actually encourage a better name moving forward.

So what if we did add a new set of functions and named them `logLoc` and `logLocM`. These would be the ones where CPP would make them log location for new GHCs and just be a plain log statement for old GHCs, documented accordingly. 

If that is agreeable, we can move onto schedule: is there a good reason to ever deprecate the TH version? Is the idea that TH slows down compilation or unnecessarily forces recompiles sometimes? Or is the idea more that once 7.8 support is dropped, there really is no advantage to using the TH version? In either case, without a clear date for when 7.8 support is dropped, we can just worry about deprecation warnings later and make prominent note of the new functions in release notes.

On the last issue that ibotty raises: I do think it would be useful to have the ability to log callstacks. I've created issue #19 to discuss this further :)

**Comment by adinapoli** [comment]
Hey @MichaelXavier , thanks for bringing us out of the bikeshedding swamps :trollface: 

What you propose makes a great deal of sense. Will amend this PR accordingly!

**Comment by adinapoli** [comment]
@MichaelXavier ok, we should be in business! Do you think this is good enough or it needs further clarification/refining? 

Travis seems to fail the last 2 jobs with errors unrelated to my PR, it seems. What do you think shall I do here?

**Comment by MichaelXavier** [comment]
@adinapoli yeah I'm pretty sure those buffer errors are related to an issue with TLS (which recently got fixed). Don't sweat it. This PR looks perfect. Thanks for rolling with the punches on this one! I'll go ahead and merge this and take care of any resulting breakage.

**Comment by adinapoli** [comment]
Yay, we did it! Thanks for the support and the nice discussion/brainstorming, @MichaelXavier !

**Pull request merged**
