### PR TITLE
Implement `logKatipItem` to log the Item

### PR DESCRIPTION
**Pull request by vlatkoB**
A new low-level function that logs the Item itself. `logItem` reimplemented to use this function. 
Version raised to 0.8.3.0

### CODE REVIEW

**Comment by vlatkoB** [comment]
Oh, boy. Seems I made some mess. :-(
Let me see if I can clean that up. Might take some time, have to leave now.

**Comment by vlatkoB** [comment]
Let me know if you want to discard this PR and I can send it again.

**Comment by MichaelXavier** [comment]
Is this going to introduce all 35 of these commits to the history? If so then it would be helpful to maybe do a redo.

**Comment by vlatkoB** [comment]
I'm not sure, never merged on GitHub. I fixed it on my side, and it seems all is fine. That fix was my last commit.
Feel free to delete it and I'll resend it.

**Pull request closed without merging**
