### PR TITLE
Allow katip to be build under Windows.

### PR DESCRIPTION
**Pull request by qnikst**

### CODE REVIEW

**Comment by MichaelXavier** [comment]
Thanks!

**Comment by MichaelXavier** [comment]
Could you advise what version number bump should happen here? If this never worked on windows could we get away with an `C` change in `A.B.C`?

**Comment by qnikst** [comment]
I think it's completely OK to bump `A.B.C`

**Comment by MichaelXavier** [comment]
This is released on version 0.3.1.3. Thanks again!

**Pull request merged**
