### PR TITLE
(Breaking change) Faster Handle Scribe

### PR DESCRIPTION
**Pull request by adinapoli**
Hey @MichaelXavier ,

as per #46 I have played around with `unagi-chan` in order to speed up the performances of the `Handle` `Scribe`. Before delving into the details these are the results, where topmost is the old bench, bottom is the new implementation:

```
katip-0.3.1.4: benchmarks
Running 1 benchmarks...
Benchmark bench: RUNNING...
benchmarking Katip.Scribes.Handle/Bytestring Builder
time                 5.759 μs   (5.683 μs .. 5.857 μs)
                     0.998 R²   (0.998 R² .. 0.999 R²)
mean                 5.755 μs   (5.703 μs .. 5.827 μs)
std dev              201.7 ns   (166.8 ns .. 233.3 ns)
variance introduced by outliers: 44% (moderately inflated)

Benchmark bench: FINISH

katip-0.3.1.4: benchmarks
Running 1 benchmarks...
Benchmark bench: RUNNING...
benchmarking Katip.Scribes.Handle/Bytestring Builder
time                 38.29 ns   (37.75 ns .. 39.00 ns)
                     0.998 R²   (0.996 R² .. 0.999 R²)
mean                 38.30 ns   (37.92 ns .. 38.87 ns)
std dev              1.442 ns   (1.000 ns .. 1.927 ns)
variance introduced by outliers: 59% (severely inflated)
```

As you can see, quite an improvement!

There are a couple of things to consider here though:

* The implementation is built for speed and right now it will drop messages if the queue is full (cfr `tryReadChan`)
* There is **absolutely no** story for resource cleanup, which means that if one stops abruptly the program and there are messages left in the queue, the async will die and those messages won't be delivered. I have already stubbed out a cleanup mechanism via a `PoisonPill` that we should deliver to the `worker` when we stop, but currently there is no way of doing that without either breaking the `mkHandleScribe` API or rework the internals of Katip (as per #46).

Therefore, I have issued this PR anyway but I would consider more a preview more than anything else, unless you think that:

1. The performance gains is such that we should merge this anyway
2. We could create a `mkHandleScribeUnsafe` logger which would use this implementation but warn the user about the implications
3. We use this as a start for a discussion but leave it unmerged.

Whatever you decide I'm cool with that!

A.

### CODE REVIEW

**Comment by MichaelXavier** [comment]
This looks really good, thank you! Its a shame unagi-chan doesn't have a closeable variant. Your `PoisonPill` variation is clever. I can't think of another way to do it because unagi-chan splits into 2 channels, an in and an out side. We could possibly create a wrapper like `data Closeable a = Closeable (MVar Bool) a`, share the mvar (or tvar or whatever is appropriate) between both sides such that write operations are a noop when an InChan is closed and a closed OutChan means its time to die. However, this is sounding a whole lot more complicated and probably worse performance than the semantics of a poison pill.

Handle skirted the issue of cleanup so far by taking a handle from input, thus shirking the responsibility of cleaning it up. Katip elastic search already dealt with this issue by [returning a finalizer](https://github.com/Soostone/katip/blob/master/katip-elasticsearch/src/Katip/Scribes/ElasticSearch.hs#L264). Perhaps we should bite the bullet and make that small API change now so that your handle scribe returns an action that enqueues the poison pill? I think somewhere in the docs I may even have guidelines for writing scribes so that would be worth adding a note that scribes should return a tuple with a finalizer if applicable.

**Comment by MichaelXavier** [comment]
One small thing worth mentioning is that katip-elasticsearch's finalizing function is blocking which is probably something we want to preserve. The idea is that you would put it at the end of your program's lifecycle and when it returns, that means all writes have been committed and its safe to close. I think you could do this simply by having your finalizer be something like `writeChan inChan PoisionPill >> void (waitCatchAsync worker)` or something like that.

**Comment by adinapoli** [comment]
Hey Michael!

> Perhaps we should bite the bullet and make that small API change now so that your handle scribe returns an action that enqueues the poison pill?

Believe it or not that was the solution I was leaning towards, but I refrained doing that as I thought breaking the API would have made you not so happy 😉 

Jokes aside, I think that is a very sensible idea and I can actually see a pattern emerging here (maybe something we could address as part of #49 ? ) It we would extend the `Scribe` type with not only the "push" action **and** a new field storing a finaliser of some sort, we could lift the finalisation story into the guts of Katip and relief the users from doing that. But maybe that's not that simple and we need to go back to the drawing board 😝 

As far as this PR is concerned, I'm very happy with whatever you decide: possibly the morally right thing to do would be here to bite the bullet and change the API of `mkHandleScribe` to return (Scribe, IO ()), so that at least we give the user the chance to have the piece of mind of having all the logs delivered?

**Comment by adinapoli** [comment]
I have been thinking about this, and I'm definitely going (if you are OK with that) to break the API and modify the `mkHandleScribe` signature to be `IO (Scribe, IO ())`.

One compelling reason I have found is that otherwise we have no way to make tests reproducible, and that's the reason of part of the travis failure (the other part is me being lazy and not adding the necessary deps to the stack-XX.yml files).

@MichaelXavier what do you think? 👍  or 👎  ?

**Comment by MichaelXavier** [comment]
This look great to me. I'd say keep the finalizer pair like you have it. My plan with this is to merge it into master and then hopefully solve 2 problems before a release:

1. Figure out a reasonably compatible strategy to get katip-elasticsearch on bloodhound 0.13 (it changed module structure)
2. Get this internal channel in katip built and have it delegate finalization/removal actions.

I hope you're ok with submoduling or otherwise vendoring katip in the meantime to get the improved performance. I've got a couple of production gremlins to troubleshoot before I can get to this other implementation work. It looks like the examples dir needs a quick update to account for the finalizer and then a few of the LTSes may need extra-deps in their stack.yaml files, but otherwise this looks sound to me! Thank you!

**Comment by adinapoli** [comment]
@MichaelXavier ok, we should be good to go! 😉

**Comment by MichaelXavier** [comment]
Thanks!

**Pull request merged**
